apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-node
  name: hello-node
  namespace: default
spec:
  ports:
  - targetPort: {{ .Values.service.port }}
    port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: hello-node
  sessionAffinity: None
  type: {{ .Values.service.type }}
